import type { Metadata } from "next";
import { ReactNode } from "react";
import MainHeader from "../../components/main-header/MainHeader";

export const metadata: Metadata = {
  title: "Test site",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="uk">
      <head>
        <title>My website</title>
      </head>
      <body>
        <MainHeader />
        <div>
          <p>Hello there!</p>
          {children}
        </div>
      </body>
    </html>
  );
}
